<a href="https://colab.research.google.com/github/luzdelcarmenRuiz/PythonCienciaDatos/blob/main/arreglos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arreglo=np.array([1,2,3,4,5])
print(arreglo)
print(arreglo[0])

[1 2 3 4 5]
1


In [11]:
arreglo_2=np.array([[1,2,3],[4,5,6]])
print(arreglo_2.ndim)
print(arreglo_2)
print('Segundo elemento del arreglo:',arreglo_2[0,1])

2
[[1 2 3]
 [4 5 6]]
Segundo elemento del arreglo: 2


In [7]:
arreglo_3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arreglo_3.ndim)
print(arreglo_3)

3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
arreglo_4=np.array([41,32,28,17])
print(arreglo_4[2]+arreglo_4[3])

print(arreglo_4[1:3])
print(arreglo_4[::2])
print(arreglo_4.shape)

45
[32 28]
[41 28]
(4,)


In [4]:
arreglo_5=np.array([1,2,3,4,5,6,7,8,9])
arreglo_6=arreglo_5.reshape(3,3)
print(arreglo_6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
arreglo_7=np.array([[1,2,3,4,5],[6,7,8,9,10],[5,4,3,2,7]])
for i in arreglo_7:
  for j in i:
    print(j)

#ordena el arreglo en su totalidad
print(np.sort(arreglo_7,axis=None))
print()

#ordena los elementos de cada renglon
print(np.sort(arreglo_7,axis=1))

#ordena los elementos de cada columna
print(np.sort(arreglo_7,axis=0))

1
2
3
4
5
6
7
8
9
10
5
4
3
2
7
[ 1  2  2  3  3  4  4  5  5  6  7  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 2  3  4  5  7]]
[[ 1  2  3  2  5]
 [ 5  4  3  4  7]
 [ 6  7  8  9 10]]
